require:
  - ./lib/rubocop/cop/style/method_order

AllCops:
  Exclude:
    - test/fixtures/files/**/*
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Exclude:
    - test/**/*_test.rb
Style/MethodOrder:
  Exclude:
    - test/**/*_test.rb
