sudo: false
language: ruby
rvm:
  - jruby-head
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
before_install:
  - gem update --system
  - gem update --remote bundler
install:
  - bundle install --retry=3
